<a href="https://www.kaggle.com/code/puneetkoundal/pytorch-training-pipeline?scriptVersionId=230694779" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import numpy as np
import pandas as pd
import torch 

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df.head()

/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pan

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)
df.shape

(569, 31)

In [5]:
X_train , X_test , y_train , y_test = train_test_split(df.iloc[ : , 1: ], df.iloc[:,0] , test_size=0.2)
X_train

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
474        10.88         15.62           70.41      358.9          0.10070   
229        12.83         22.33           85.26      503.2          0.10880   
47         13.17         18.66           85.98      534.6          0.11580   
250        20.94         23.56          138.90     1364.0          0.10070   
7          13.71         20.83           90.20      577.9          0.11890   
..           ...           ...             ...        ...              ...   
428        11.13         16.62           70.47      381.1          0.08151   
392        15.49         19.97          102.40      744.7          0.11600   
207        17.01         20.26          109.70      904.3          0.08772   
31         11.84         18.70           77.93      440.6          0.11090   
10         16.02         23.24          102.70      797.8          0.08206   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
474           0.10690         0.05115              0.01571         0.1861   
229           0.17990         0.16950              0.06861         0.2123   
47            0.12310         0.12260              0.07340         0.2128   
250           0.16060         0.27120              0.13100         0.2205   
7             0.16450         0.09366              0.05985         0.2196   
..                ...             ...                  ...            ...   
428           0.03834         0.01369              0.01370         0.1511   
392           0.15620         0.18910              0.09113         0.1929   
207           0.07304         0.06950              0.05390         0.2026   
31            0.15160         0.12180              0.05182         0.2301   
10            0.06669         0.03299              0.03323         0.1528   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
474                 0.06837  ...         11.94          19.35   
229                 0.07254  ...         15.20          30.15   
47                  0.06777  ...         15.67          27.95   
250                 0.05898  ...         25.58          27.00   
7                   0.07451  ...         17.06          28.14   
..                      ...  ...           ...            ...   
428                 0.06148  ...         11.68          20.29   
392                 0.06744  ...         21.20          29.41   
207                 0.05223  ...         19.80          25.05   
31                  0.07799  ...         16.82          28.12   
10                  0.05697  ...         19.19          33.88   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
474            80.78       433.1            0.1332            0.38980   
229           105.30       706.0            0.1777            0.53430   
47            102.80       759.4            0.1786            0.41660   
250           165.30      2010.0            0.1211            0.31720   
7             110.60       897.0            0.1654            0.36820   
..               ...         ...               ...                ...   
428            74.35       421.1            0.1030            0.06219   
392           142.10      1359.0            0.1681            0.39130   
207           130.00      1210.0            0.1111            0.14860   
31            119.40       888.7            0.1637            0.57750   
10            123.80      1150.0            0.1181            0.15510   

     concavity_worst  concave points_worst  symmetry_worst  \
474           0.3365               0.07966          0.2581   
229           0.6282               0.19770          0.3407   
47            0.5006               0.20880          0.3900   
250           0.6991               0.21050          0.3126   
7             0.2678               0.15560          0.3196   
..               ...                   ...             ...   
428           0.0458               0.04044         

In [6]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)
y_train

array([0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0,

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


In [8]:
#transformning numpy array to pytorch tensor

In [9]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)


In [10]:
X_train_tensor

tensor([[-0.9050, -0.8255, -0.8713,  ..., -0.5311, -0.5092,  1.2976],
        [-0.3614,  0.7303, -0.2711,  ...,  1.2515,  0.8328,  2.1816],
        [-0.2666, -0.1207, -0.2420,  ...,  1.4191,  1.6338,  1.8345],
        ...,
        [ 0.8038,  0.2503,  0.7166,  ..., -0.0790,  0.6184, -1.0511],
        [-0.6374, -0.1114, -0.5674,  ...,  0.6006,  3.0327,  3.0439],
        [ 0.5278,  0.9413,  0.4337,  ..., -0.2278,  0.0871,  0.0243]],
       dtype=torch.float64)

In [11]:
y_train_tensor.shape

torch.Size([455])

In [12]:
#nueral network
X_train_tensor.shape[1]

30

In [13]:
class mysimpleNN():
    def __init__(self,X):
        self.weight = torch.rand(X.shape[1],1,dtype=torch.
                                 float64 , requires_grad=True)
        self.bias = torch.rand(1,dtype=torch.float64,requires_grad = True)
        
    def forward(self,X,):
        z=torch.matmul(X,self.weight) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred

    
    def binary_cross_entropy(self,y_pred,y):
        loss = -(y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred)).mean()
        return loss




        
        



In [14]:
#important parameters

In [15]:
learning_rate = 0.1
epochs =25


In [16]:
model = mysimpleNN(X_train_tensor)
for epoch in range(epochs) :
    y_pred = model.forward(X_train_tensor)
    
    loss = model.binary_cross_entropy(y_pred,y_train_tensor)
    print(f'epoch: {epoch+1}, loss: {loss.item()}')

    
    loss.backward()
    with torch.no_grad():
        model.weight -= learning_rate * model.weight.grad
        model.bias -= learning_rate * model.bias.grad

    
    model.weight.grad.zero_()
    model.bias.grad.zero_()
    print(f'epoch {epoch+1},loss:{loss.item()}')

    

epoch: 1, loss: 3.294548201298006
epoch 1,loss:3.294548201298006
epoch: 2, loss: 3.102333895765665
epoch 2,loss:3.102333895765665
epoch: 3, loss: 2.9140277761608226
epoch 3,loss:2.9140277761608226
epoch: 4, loss: 2.730308961679394
epoch 4,loss:2.730308961679394
epoch: 5, loss: 2.5519232692794516
epoch 5,loss:2.5519232692794516
epoch: 6, loss: 2.379671631109368
epoch 6,loss:2.379671631109368
epoch: 7, loss: 2.2143864442089747
epoch 7,loss:2.2143864442089747
epoch: 8, loss: 2.056929438063453
epoch 8,loss:2.056929438063453
epoch: 9, loss: 1.9081967199109877
epoch 9,loss:1.9081967199109877
epoch: 10, loss: 1.7691175719725996
epoch 10,loss:1.7691175719725996
epoch: 11, loss: 1.6406316607678582
epoch 11,loss:1.6406316607678582
epoch: 12, loss: 1.5236351711118687
epoch 12,loss:1.5236351711118687
epoch: 13, loss: 1.4188950606924084
epoch 13,loss:1.4188950606924084
epoch: 14, loss: 1.3269380080822162
epoch 14,loss:1.3269380080822162
epoch: 15, loss: 1.2479273825932318
epoch 15,loss:1.2479273825

In [17]:
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.9).float()
    
print(y_pred)
    

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
      

In [18]:
accuracy = (y_pred == y_test_tensor).float().mean()
print(f'accurac: {accuracy.item()}')

accurac: 0.559556782245636
